BRIGHT_STARS = [
    {
        "id": "sirius",
        "name": "Sirius",
        "object_type": "star",
        "constellation": "Canis Major",
        "constellation_code": "CMa",
        "magnitude": -1.46,
        "ra_hours": 6.7525,
        "dec_deg": -16.7161,
    },
    {
        "id": "canopus",
        "name": "Canopus",
        "object_type": "star",
        "constellation": "Carina",
        "constellation_code": "Car",
        "magnitude": -0.74,
        "ra_hours": 6.3992,
        "dec_deg": -52.6957,
    },
    {
        "id": "arcturus",
        "name": "Arcturus",
        "object_type": "star",
        "constellation": "Boötes",
        "constellation_code": "Boo",
        "magnitude": -0.05,
        "ra_hours": 14.2610,
        "dec_deg": 19.1824,
    },
    {
        "id": "vega",
        "name": "Vega",
        "object_type": "star",
        "constellation": "Lyra",
        "constellation_code": "Lyr",
        "magnitude": 0.03,
        "ra_hours": 18.6156,
        "dec_deg": 38.7837,
    },
    {
        "id": "capella",
        "name": "Capella",
        "object_type": "star",
        "constellation": "Auriga",
        "constellation_code": "Aur",
        "magnitude": 0.08,
        "ra_hours": 5.2782,
        "dec_deg": 45.9980,
    },
    {
        "id": "rigel",
        "name": "Rigel",
        "object_type": "star",
        "constellation": "Orion",
        "constellation_code": "Ori",
        "magnitude": 0.13,
        "ra_hours": 5.2423,
        "dec_deg": -8.2016,
    },
    {
        "id": "procyon",
        "name": "Procyon",
        "object_type": "star",
        "constellation": "Canis Minor",
        "constellation_code": "CMi",
        "magnitude": 0.34,
        "ra_hours": 7.6550,
        "dec_deg": 5.2250,
    },
    {
        "id": "betelgeuse",
        "name": "Betelgeuse",
        "object_type": "star",
        "constellation": "Orion",
        "constellation_code": "Ori",
        "magnitude": 0.50,
        "ra_hours": 5.9195,
        "dec_deg": 7.4071,
    },
    {
        "id": "achernar",
        "name": "Achernar",
        "object_type": "star",
        "constellation": "Eridanus",
        "constellation_code": "Eri",
        "magnitude": 0.46,
        "ra_hours": 1.6286,
        "dec_deg": -57.2368,
    },
    {
        "id": "hadar",
        "name": "Hadar",
        "object_type": "star",
        "constellation": "Centaurus",
        "constellation_code": "Cen",
        "magnitude": 0.61,
        "ra_hours": 14.0637,
        "dec_deg": -60.3730,
    },
    {
        "id": "altair",
        "name": "Altair",
        "object_type": "star",
        "constellation": "Aquila",
        "constellation_code": "Aql",
        "magnitude": 0.77,
        "ra_hours": 19.8464,
        "dec_deg": 8.8683,
    },
    {
        "id": "acrux",
        "name": "Acrux",
        "object_type": "star",
        "constellation": "Crux",
        "constellation_code": "Cru",
        "magnitude": 0.76,
        "ra_hours": 12.4433,
        "dec_deg": -63.0991,
    },
    {
        "id": "aldebaran",
        "name": "Aldebaran",
        "object_type": "star",
        "constellation": "Taurus",
        "constellation_code": "Tau",
        "magnitude": 0.85,
        "ra_hours": 4.5987,
        "dec_deg": 16.5093,
    },
    {
        "id": "antares",
        "name": "Antares",
        "object_type": "star",
        "constellation": "Scorpius",
        "constellation_code": "Sco",
        "magnitude": 0.96,
        "ra_hours": 16.4901,
        "dec_deg": -26.4320,
    },
    {
        "id": "spica",
        "name": "Spica",
        "object_type": "star",
        "constellation": "Virgo",
        "constellation_code": "Vir",
        "magnitude": 0.98,
        "ra_hours": 13.4199,
        "dec_deg": -11.1613,
    },
    {
        "id": "pollux",
        "name": "Pollux",
        "object_type": "star",
        "constellation": "Gemini",
        "constellation_code": "Gem",
        "magnitude": 1.14,
        "ra_hours": 7.7553,
        "dec_deg": 28.0262,
    },
    {
        "id": "fomalhaut",
        "name": "Fomalhaut",
        "object_type": "star",
        "constellation": "Piscis Austrinus",
        "constellation_code": "PsA",
        "magnitude": 1.16,
        "ra_hours": 22.9608,
        "dec_deg": -29.6222,
    },
    {
        "id": "deneb",
        "name": "Deneb",
        "object_type": "star",
        "constellation": "Cygnus",
        "constellation_code": "Cyg",
        "magnitude": 1.25,
        "ra_hours": 20.6905,
        "dec_deg": 45.2803,
    },
    {
        "id": "regulus",
        "name": "Regulus",
        "object_type": "star",
        "constellation": "Leo",
        "constellation_code": "Leo",
        "magnitude": 1.35,
        "ra_hours": 10.1395,
        "dec_deg": 11.9672,
    },
    {
        "id": "castor",
        "name": "Castor",
        "object_type": "star",
        "constellation": "Gemini",
        "constellation_code": "Gem",
        "magnitude": 1.58,
        "ra_hours": 7.5767,
        "dec_deg": 31.8883,
    },
    {
        "id": "bellatrix",
        "name": "Bellatrix",
        "object_type": "star",
        "constellation": "Orion",
        "constellation_code": "Ori",
        "magnitude": 1.64,
        "ra_hours": 5.4189,
        "dec_deg": 6.3497,
    },
    {
        "id": "elnath",
        "name": "Elnath",
        "object_type": "star",
        "constellation": "Taurus",
        "constellation_code": "Tau",
        "magnitude": 1.65,
        "ra_hours": 5.4382,
        "dec_deg": 28.6075,
    },
    {
        "id": "alnilam",
        "name": "Alnilam",
        "object_type": "star",
        "constellation": "Orion",
        "constellation_code": "Ori",
        "magnitude": 1.69,
        "ra_hours": 5.6036,
        "dec_deg": -1.2019,
    },
    {
        "id": "alnair",
        "name": "Alnair",
        "object_type": "star",
        "constellation": "Grus",
        "constellation_code": "Gru",
        "magnitude": 1.74,
        "ra_hours": 22.1372,
        "dec_deg": -46.9610,
    },
    {
        "id": "alioth",
        "name": "Alioth",
        "object_type": "star",
        "constellation": "Ursa Major",
        "constellation_code": "UMa",
        "magnitude": 1.76,
        "ra_hours": 12.9005,
        "dec_deg": 55.9598,
    },
    {
        "id": "mirfak",
        "name": "Mirfak",
        "object_type": "star",
        "constellation": "Perseus",
        "constellation_code": "Per",
        "magnitude": 1.79,
        "ra_hours": 3.4054,
        "dec_deg": 49.8612,
    },
    {
        "id": "dubhe",
        "name": "Dubhe",
        "object_type": "star",
        "constellation": "Ursa Major",
        "constellation_code": "UMa",
        "magnitude": 1.79,
        "ra_hours": 11.0621,
        "dec_deg": 61.7508,
    },
    {
        "id": "alkaid",
        "name": "Alkaid",
        "object_type": "star",
        "constellation": "Ursa Major",
        "constellation_code": "UMa",
        "magnitude": 1.86,
        "ra_hours": 13.7923,
        "dec_deg": 49.3133,
    },
    {
        "id": "sargas",
        "name": "Sargas",
        "object_type": "star",
        "constellation": "Scorpius",
        "constellation_code": "Sco",
        "magnitude": 1.86,
        "ra_hours": 17.6219,
        "dec_deg": -42.9978,
    },
    {
        "id": "kochab",
        "name": "Kochab",
        "object_type": "star",
        "constellation": "Ursa Minor",
        "constellation_code": "UMi",
        "magnitude": 2.08,
        "ra_hours": 14.8451,
        "dec_deg": 74.1555,
    },
]
