IAU_CONSTELLATION_COUNT = 88

CONSTELLATIONS_FR = {
    "And": "Andromède",
    "Ant": "Machine pneumatique",
    "Aps": "Oiseau de paradis",
    "Aql": "Aigle",
    "Aqr": "Verseau",
    "Ara": "Autel",
    "Ari": "Bélier",
    "Aur": "Cocher",
    "Boo": "Bouvier",
    "Cae": "Burin",
    "Cam": "Girafe",
    "Cnc": "Cancer",
    "CVn": "Chiens de chasse",
    "CMa": "Grand Chien",
    "CMi": "Petit Chien",
    "Cap": "Capricorne",
    "Car": "Carène",
    "Cas": "Cassiopée",
    "Cen": "Centaure",
    "Cep": "Céphée",
    "Cet": "Baleine",
    "Cha": "Caméléon",
    "Cir": "Compas",
    "Col": "Colombe",
    "Com": "Chevelure de Bérénice",
    "CrA": "Couronne australe",
    "CrB": "Couronne boréale",
    "Crt": "Coupe",
    "Cru": "Croix du Sud",
    "Crv": "Corbeau",
    "Cyg": "Cygne",
    "Del": "Dauphin",
    "Dor": "Dorade",
    "Dra": "Dragon",
    "Equ": "Petit Cheval",
    "Eri": "Éridan",
    "For": "Fourneau",
    "Gem": "Gémeaux",
    "Gru": "Grue",
    "Her": "Hercule",
    "Hor": "Horloge",
    "Hya": "Hydre",
    "Hyi": "Hydre mâle",
    "Ind": "Indien",
    "Lac": "Lézard",
    "Leo": "Lion",
    "Lep": "Lièvre",
    "Lib": "Balance",
    "LMi": "Petit Lion",
    "Lup": "Loup",
    "Lyn": "Lynx",
    "Lyr": "Lyre",
    "Men": "Table",
    "Mic": "Microscope",
    "Mon": "Licorne",
    "Mus": "Mouche",
    "Nor": "Règle",
    "Oct": "Octant",
    "Oph": "Ophiuchus",
    "Ori": "Orion",
    "Pav": "Paon",
    "Peg": "Pégase",
    "Per": "Persée",
    "Phe": "Phénix",
    "Pic": "Peintre",
    "PsA": "Poisson austral",
    "Psc": "Poissons",
    "Pup": "Poupe",
    "Pyx": "Boussole",
    "Ret": "Réticule",
    "Sge": "Flèche",
    "Sgr": "Sagittaire",
    "Sco": "Scorpion",
    "Scl": "Sculpteur",
    "Sct": "Écu de Sobieski",
    "Ser": "Serpent",
    "Se1": "Serpent (Tête)",
    "Se2": "Serpent (Queue)",
    "Sex": "Sextant",
    "Tau": "Taureau",
    "Tel": "Télescope",
    "TrA": "Triangle austral",
    "Tri": "Triangle",
    "Tuc": "Toucan",
    "UMa": "Grande Ourse",
    "UMi": "Petite Ourse",
    "Vel": "Voiles",
    "Vir": "Vierge",
    "Vol": "Poisson volant",
    "Vul": "Petit Renard",
}


def constellation_fr(code: str | None) -> str | None:
    if not code:
        return None

    return CONSTELLATIONS_FR.get(
        code.strip(),
        code.strip(),
    )
